# Generated by Django 6.0.1 on 2026-02-09 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_comment_text_listing_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='img_url',
            new_name='image_url',
        ),
    ]
